name: Build and deploy KoffBot UI to Azure

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and deploy KoffBot UI
    runs-on: ubuntu-latest

    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1.4.6
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS_PROD }}"

      - name: "Checkout GitHub Action"
        uses: actions/checkout@master

      - name: Install packages
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/src
          yarn

      - name: Build app
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/src
          yarn build

      - name: Upload to blob storage
        uses: azure/CLI@master
        with:
          inlineScript: |
            az storage blob upload-batch --account-name storageaccountkoffbab19 --auth-mode key -d '$web' -s $GITHUB_WORKSPACE/dist --overwrite

      - name: Purge CDN endpoint
        uses: azure/CLI@master
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name "KoffBot" --name "KoffBot" --resource-group "KoffBot"
